use thrust_macros::service;

/// Abstraction the services depend on, rather than a concrete repository.
/// A bare `dyn UserRepository` field on a `#[service]` is compiled to
/// `Arc<dyn UserRepository + Send + Sync>` (dynamic dispatch). The concrete impl
/// is still resolved at build time for container wiring, but the field stays a
/// trait object — identical in tests and production, so it can be mocked. The
/// `Send + Sync` bound is added at the field use-site, so the trait stays clean.
///
/// `#[cfg_attr(test, automock)]` makes `mockall` generate a `MockUserRepository`
/// in test builds only — no mock code ships in release. The generated mock
/// covers *every* method, but each test sets expectations only on the methods it
/// actually exercises (see the `tests` module below).
#[cfg_attr(test, mockall::automock)]
pub trait UserRepository {
    fn find_user(&self) -> String;
    fn count_users(&self) -> usize;
}

#[service]
pub struct PostgresUserRepository;

impl UserRepository for PostgresUserRepository {
    fn find_user(&self) -> String {
        "user from postgres".to_string()
    }
    fn count_users(&self) -> usize {
        42
    }
}

#[service]
pub struct UserService {
    pub repo: dyn UserRepository,
}

#[service]
pub struct EmailService {
    pub repo: dyn UserRepository,
}

impl UserService {
    pub fn hello(&self) -> String {
        format!("hello from UserService — {}", self.repo.find_user())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;

    // `MockUserRepository` is generated by `#[automock]` on the trait. The
    // `#[service]` macro compiles `UserService::repo` as
    // `Arc<dyn UserRepository + Send + Sync>` in every build, so the mock drops
    // straight into the field — no hand-written impl, no struct per scenario.

    #[test]
    fn hello_uses_injected_repo() {
        let mut repo = MockUserRepository::new();
        // Only `find_user` is set up. `count_users` is never expected because
        // `hello()` never calls it — and if it did, the test would fail loudly.
        repo.expect_find_user().return_const("mock user".to_string());

        let service = UserService {
            repo: Arc::new(repo),
        };
        assert_eq!(service.hello(), "hello from UserService — mock user");
    }

    #[test]
    fn hello_with_a_different_user() {
        // Same mock type, different behaviour — no second struct needed.
        let mut repo = MockUserRepository::new();
        repo.expect_find_user().returning(|| "alice".to_string());

        let service = UserService {
            repo: Arc::new(repo),
        };
        assert_eq!(service.hello(), "hello from UserService — alice");
    }

    #[test]
    fn find_user_is_called_exactly_once() {
        // Expectations can also assert *interactions*, not just return values.
        let mut repo = MockUserRepository::new();
        repo.expect_find_user()
            .times(1)
            .return_const("once".to_string());

        let service = UserService {
            repo: Arc::new(repo),
        };
        service.hello();
        // `times(1)` is verified when the mock is dropped.
    }
}
